import { z } from "zod";

export const InstagramPostSchema = z.object({
  id: z.string().nullish(),
  postType: z.string().nullish(),
  userId: z.string().nullish(),
  username: z.string().nullish(),
  fullName: z.string().nullish(),
  caption: z.string().nullish(),
  mediaType: z.string().nullish(),
  codeUrl: z.string().nullish(),
  imageUrl: z.string().nullish(),
  videoUrl: z.string().nullish(),
  audioOnlyUrl: z.string().nullish(),
  profilePicUrl: z.string().nullish(),
  videoSubtitlesUri: z.string().nullish(),
  subtitles: z.string().nullish(),
  videoDuration: z.number().nullish(),
  likeCount: z.number().nullish(),
  commentCount: z.number().nullish(),
  reshareCount: z.number().nullish(),
  videoPlayCount: z.number().nullish(),
  location: z.string().nullish(),
  createdAt: z.string().nullish(),
  createdAtTimestamp: z.number().nullish(),
  createdAtDate: z.string().nullish(),
}).passthrough();

export const InstagramUserSchema = z.object({
  id: z.string().nullish(),
  username: z.string().nullish(),
  fullName: z.string().nullish(),
  biography: z.string().nullish(),
  isPrivate: z.boolean().nullish(),
  isVerified: z.boolean().nullish(),
  followerCount: z.number().nullish(),
  followingCount: z.number().nullish(),
  mediaCount: z.number().nullish(),
  profilePicUrl: z.string().nullish(),
  profilePicId: z.string().nullish(),
  profileUrl: z.string().nullish(),
  externalUrl: z.string().nullish(),
  hasAnonymousProfilePicture: z.boolean().nullish(),
}).passthrough();

export const InstagramCommentSchema = z.object({
  id: z.string().nullish(),
  text: z.string().nullish(),
  parentPostId: z.string().nullish(),
  parentPostUserId: z.string().nullish(),
  type: z.string().nullish(),
  parentCommentId: z.string().nullish(),
  repliedToCommentId: z.string().nullish(),
  childCommentCount: z.number().nullish(),
  userId: z.string().nullish(),
  username: z.string().nullish(),
  fullName: z.string().nullish(),
  likeCount: z.number().nullish(),
  status: z.string().nullish(),
  isSpam: z.boolean().nullish(),
  hasTranslation: z.boolean().nullish(),
  createdAt: z.string().nullish(),
  createdAtTimestamp: z.number().nullish(),
  createdAtDate: z.string().nullish(),
}).passthrough();
