import { z } from "zod";

export const RedditPostSchema = z.object({
  id: z.string().nullish(),
  title: z.string().nullish(),
  selftext: z.string().nullish(),
  url: z.string().nullish(),
  permalink: z.string().nullish(),
  postUrl: z.string().nullish(),
  thumbnail: z.string().nullish(),
  authorId: z.string().nullish(),
  authorUsername: z.string().nullish(),
  subredditName: z.string().nullish(),
  subredditId: z.string().nullish(),
  score: z.number().nullish(),
  upvotes: z.number().nullish(),
  downvotes: z.number().nullish(),
  upvoteRatio: z.number().nullish(),
  commentsCount: z.number().nullish(),
  crosspostsCount: z.number().nullish(),
  isSelf: z.boolean().nullish(),
  isVideo: z.boolean().nullish(),
  isOriginalContent: z.boolean().nullish(),
  over18: z.boolean().nullish(),
  spoiler: z.boolean().nullish(),
  locked: z.boolean().nullish(),
  stickied: z.boolean().nullish(),
  archived: z.boolean().nullish(),
  linkFlairText: z.string().nullish(),
  postHint: z.string().nullish(),
  domain: z.string().nullish(),
  crosspostParent: z.string().nullish(),
  createdAt: z.string().nullish(),
  createdAtTimestamp: z.number().nullish(),
  createdAtDate: z.string().nullish(),
}).passthrough();

export const RedditUserSchema = z.object({
  id: z.string().nullish(),
  username: z.string().nullish(),
  profileUrl: z.string().nullish(),
  profilePicUrl: z.string().nullish(),
  snoovatarImg: z.string().nullish(),
  linkKarma: z.number().nullish(),
  commentKarma: z.number().nullish(),
  totalKarma: z.number().nullish(),
  awardeeKarma: z.number().nullish(),
  awarderKarma: z.number().nullish(),
  isGold: z.boolean().nullish(),
  isMod: z.boolean().nullish(),
  isEmployee: z.boolean().nullish(),
  hasVerifiedEmail: z.boolean().nullish(),
  isSuspended: z.boolean().nullish(),
  verified: z.boolean().nullish(),
  isBlocked: z.boolean().nullish(),
  acceptFollowers: z.boolean().nullish(),
  hasSubscribed: z.boolean().nullish(),
  hideFromRobots: z.boolean().nullish(),
  prefShowSnoovatar: z.boolean().nullish(),
  profileDescription: z.string().nullish(),
  profileBannerUrl: z.string().nullish(),
  profileTitle: z.string().nullish(),
  createdAt: z.string().nullish(),
  createdAtTimestamp: z.number().nullish(),
  createdAtDate: z.string().nullish(),
}).passthrough();

export const RedditCommentSchema = z.object({
  id: z.string().nullish(),
  body: z.string().nullish(),
  parentPostId: z.string().nullish(),
  parentId: z.string().nullish(),
  authorId: z.string().nullish(),
  authorUsername: z.string().nullish(),
  postSubredditName: z.string().nullish(),
  postSubredditId: z.string().nullish(),
  score: z.number().nullish(),
  upvotes: z.number().nullish(),
  downvotes: z.number().nullish(),
  controversiality: z.number().nullish(),
  depth: z.number().nullish(),
  isSubmitter: z.boolean().nullish(),
  stickied: z.boolean().nullish(),
  collapsed: z.boolean().nullish(),
  edited: z.boolean().nullish(),
  distinguished: z.string().nullish(),
  createdAt: z.string().nullish(),
  createdAtTimestamp: z.number().nullish(),
  createdAtDate: z.string().nullish(),
}).passthrough();

export const RedditSubredditSchema = z.object({
  id: z.string().nullish(),
  displayName: z.string().nullish(),
  title: z.string().nullish(),
  publicDescription: z.string().nullish(),
  description: z.string().nullish(),
  subscribersCount: z.number().nullish(),
  activeUserCount: z.number().nullish(),
  subredditType: z.string().nullish(),
  over18: z.boolean().nullish(),
  lang: z.string().nullish(),
  url: z.string().nullish(),
  subredditUrl: z.string().nullish(),
  iconImg: z.string().nullish(),
  bannerImg: z.string().nullish(),
  headerImg: z.string().nullish(),
  communityIcon: z.string().nullish(),
  createdAt: z.string().nullish(),
  createdAtTimestamp: z.number().nullish(),
  createdAtDate: z.string().nullish(),
}).passthrough();
