import { z } from "zod";

export const TwitterPostSchema = z.object({
  id: z.string().nullish(),
  text: z.string().nullish(),
  authorId: z.string().nullish(),
  authorUsername: z.string().nullish(),
  conversationId: z.string().nullish(),
  lang: z.string().nullish(),
  source: z.string().nullish(),
  deleted: z.boolean().nullish(),
  suspended: z.boolean().nullish(),
  possiblySensitive: z.boolean().nullish(),
  isRetweet: z.boolean().nullish(),
  hasBirdwatchNotes: z.boolean().nullish(),
  birdwatchNotesId: z.string().nullish(),
  birdwatchNotesText: z.string().nullish(),
  birdwatchNotesUrl: z.string().nullish(),
  status: z.string().nullish(),
  likeCount: z.number().nullish(),
  retweetCount: z.number().nullish(),
  replyCount: z.number().nullish(),
  quoteCount: z.number().nullish(),
  impressionCount: z.number().nullish(),
  bookmarkCount: z.number().nullish(),
  quotedTweetId: z.string().nullish(),
  retweetedTweetId: z.string().nullish(),
  replyToTweetId: z.string().nullish(),
  replyToUserId: z.string().nullish(),
  replyToUsername: z.string().nullish(),
  originalTweetId: z.string().nullish(),
  editedTweets: z.array(z.string()).nullish(),
  hashtags: z.array(z.string()).nullish(),
  mentions: z.array(z.string()).nullish(),
  mediaUrls: z.array(z.string()).nullish(),
  urls: z.array(z.string()).nullish(),
  country: z.string().nullish(),
  region: z.string().nullish(),
  city: z.string().nullish(),
  createdAt: z.string().nullish(),
  createdAtDate: z.string().nullish(),
}).passthrough();

export const TwitterUserSchema = z.object({
  id: z.string().nullish(),
  username: z.string().nullish(),
  name: z.string().nullish(),
  description: z.string().nullish(),
  location: z.string().nullish(),
  verified: z.boolean().nullish(),
  verifiedType: z.string().nullish(),
  protected: z.boolean().nullish(),
  status: z.string().nullish(),
  followersCount: z.number().nullish(),
  followingCount: z.number().nullish(),
  tweetCount: z.number().nullish(),
  listedCount: z.number().nullish(),
  likesCount: z.number().nullish(),
  mediaCount: z.number().nullish(),
  profileImageUrl: z.string().nullish(),
  profileBannerUrl: z.string().nullish(),
  profileInterstitialType: z.string().nullish(),
  pinnedTweetId: z.string().nullish(),
  source: z.string().nullish(),
  isVerified: z.boolean().nullish(),
  accountBasedIn: z.string().nullish(),
  locationAccurate: z.boolean().nullish(),
  label: z.string().nullish(),
  labelType: z.string().nullish(),
  nLang: z.number().nullish(),
  nLangsFiltered: z.number().nullish(),
  verifiedSinceDatetime: z.string().nullish(),
  usernameChanges: z.array(z.string()).nullish(),
  lastUsernameChangeDatetime: z.string().nullish(),
  createdAt: z.string().nullish(),
  modifiedAt: z.string().nullish(),
}).passthrough();
